version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hms-postgres
    restart: always
    environment:
      POSTGRES_USER: hms_admin
      POSTGRES_PASSWORD: hms_password_2026
      POSTGRES_DB: hms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hms-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
